[package]
name = "lox-io"
description = "Interfaces for industry-standard astrodynamics file formats for the Lox ecosystem"
version = "0.1.0-alpha.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
lox-utils.workspace = true

csv.workspace = true
nom.workspace = true
serde.workspace = true
thiserror.workspace = true

quick-xml.workspace = true
serde_json.workspace = true
serde-aux.workspace = true
regex.workspace = true
fast-float.workspace = true
lox-derive.workspace = true

[dev-dependencies]
rstest.workspace = true
